### PR TITLE
added import PortugalCitiesList and exports to cities files

### PR DESCRIPTION
**Pull request by Younique98**
added export to main.js and import to cities files

### CODE REVIEW

**Review by phillip-phan-imprivata — DISMISSED** [review]
very nice

**Review by TrentSisson — DISMISSED** [review]
gtg

**Review by nicoletatum — DISMISSED** [review]

**Review by phillip-phan-imprivata — APPROVED** [review]
👍

**Review by TrentSisson — APPROVED** [review]
gtg

**Review by nicoletatum — APPROVED** [review]

**Pull request merged**
