### PR TITLE
 filled out city.js, created the city card for my cities

### PR DESCRIPTION
**Pull request by TrentSisson**
git checkout main
git fetch --all
git checkout TCS-city-js
should be able to see my fish card

### CODE REVIEW

**Review by phillip-phan-imprivata — DISMISSED** [review]
noice 👍

**Review by nicoletatum — DISMISSED** [review]
👍

**Review by phillip-phan-imprivata — APPROVED** [review]
noice pt 2

**Review by nicoletatum — COMMENTED** [review]
👍

**Review by nicoletatum — APPROVED** [review]

**Pull request merged**
