### PR TITLE
Tcs home page

### PR DESCRIPTION
**Pull request by TrentSisson**
git fetch --all
git checkout TCS-homePage
serve
should see our home page with background image

### CODE REVIEW

**Review by phillip-phan-imprivata — APPROVED** [review]
homepage looks good

**Review by nicoletatum — COMMENTED** [review]
love it. wowza

**Comment by nicoletatum** [comment]
still looks good! 
unlike my ex wife. HAHA

**Review by Younique98 — COMMENTED** [review]
Looks great. I like how you solved the background image.

**Pull request merged**
